### PR TITLE
Add GUI App (Dataflare)

### PR DESCRIPTION
**Pull request by wyhaya**
Hi rqlite, I'm the developer of Dataflare and I noticed that there is nothing about GUI App in rqlite.io yet, so I would like to add Dataflare to rqlite.io.

* This is a closed source App
* This is a paid App

I'm not sure if this meets your requirements, if not, feel free to close this PR.

Thanks rqlite.

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks for your work, but I don't want to give the impression I'm promoting this paid software.

**Comment by otoolep** [comment]
Actually, after thinking about this more, I'll find a way to add this to the rqlite.io website. I think there may be more 3rd party apps in the future, and page listing them would be useful.

Does Dataflare still support rqlite?

**Comment by wyhaya** [comment]
Yes, Dataflare supports rqlite. Although Dataflare is not yet perfect, we are continuously improving it.

For cautionary purposes, you can try using Dataflare to assess whether it meets the standards, thus avoiding any inconvenience for rqlite users.

Screenshot:
preview

**Comment by otoolep** [comment]
See https://rqlite.io/docs/api/ui/

**Comment by otoolep** [comment]
Actually, I moved it up a level in the doc hierarchy.

**Pull request closed without merging**
